spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: analysis-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo_db
  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  secret: kjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmtkjhjmt
  expiration:
    access: 600000
    refresh: 1200000

server:
  port : 8084

#eureka:
#  client:
#    # 유레카 서버에 등록 true
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/