spring:
  application:
    name: user
  profiles:
    active: service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mysql://localhost:3306/bangez_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization : true
    # open-in-view : false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: DEBUG
        web: DEBUG
        data: DEBUG
        hibernate: DEBUG
        jpa: DEBUG
        sql: DEBUG
        jwt: DEBUG

jwt:
  secret: vonvonvonvonvonvonvonvonvon
  expiration: 86400000 # a day
  refresh-token:
    expiration: 604800000 # a week

server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    shutdown:
      enabled: true

# config 서버는 기본적으로 8888번 포트를 사용
# 그 외에 설정 파일이 있는 위치와 디렉토리 매칭
# uri: 설정파일이 있는 깃 주소
# default-label: 깃 주소의 브랜치 이름
# search-paths: 설정 파일들을 찾을 경로

encrypt:
  key: my-secret