services:
  database:
    container_name: mongo-container
    image: mongo
    volumes:
      - ~/docker/mongo/db/etc/mongo/conf.d:/etc/mongo/conf.d:ro
      - ~/docker/mongo/db/var/lib/mongo:/var/lib/mongo
      - ~/docker/mongo/db/var/log/mongo:/var/log/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=mydb
    restart: always
    ports:
      - "27017:27017"
#    networks:
#      - rootnet
#  application:
#    build: .
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mongodb://mongo-container::27017/mydb
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
#    networks:
#      - rootnet
#networks:
#  rootnet:
#    driver: bridge